export const AUTH_ACTION = "AUTH_ACTION";
export const CREATE_USER_ACTION = "CREATE_USER_ACTION";
export const CREATE_EVENT_ACTION = "CREATE_EVENT_ACTION";
export const GET_EVENTS_ACTION = "GET_EVENTS_ACTION";
export const GET_BOOKINGS_ACTION = "GET_BOOKINGS_ACTION";
export const BOOK_EVENT_ACTION = "BOOK_EVENT_ACTION";
